version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    env_file:
      - ./.env

volumes: 
 data: {}
